Vagrant.configure("2") do |config|
  config.vm.box = "wholebits/ubuntu16.10-64"

  config.vm.provider "parallels" do |parallels|
    parallels.customize [ "set", :id, "--nested-virt", "on" ]
  end

  config.vm.provider "vmware_fusion" do |vmware|
    vmware.vmx["vhv.enable"] = true
  end

  config.vm.provision :shell, inline: <<-EOF
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y jq libvirt-clients libvirt-daemon make qemu-kvm qemu-utils unzip
    wget -nv https://releases.hashicorp.com/packer/0.11.0/packer_0.11.0_linux_amd64.zip
    mkdir bin
    unzip -d bin packer_0.11.0_linux_amd64.zip
    adduser vagrant kvm
    EOF

  config.vm.synced_folder "..", "/vagrant"
end
